repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
    - id: nbqa-black
    - id: nbqa-isort
    - id: nbqa-flake8
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.9.1
    hooks:
    -   id: sqlfluff-lint
-   repo: local
    hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace