#!/usr/bin/env python
"""This is an example executable. We use python fire to make our function callable.
Example calls:
    example_python_executable --help
    example_python_executable --sequence-length 20
"""
import fire

from python_package_name.example_module import get_sequence

if __name__ == "__main__":
    fire.Fire(get_sequence)
